### ISSUE TITLE
404 v1 is deprecated. 

### ISSUE THREAD

**Issue by Palmke** [ianjwhite99/connected-car-node-sdk#23]
I'm getting the following error when trying to authenticate and get a fresh token:
"404 v1 is deprecated."

**Comment by ianjwhite99** [comment]
Hi @Palmke, looks like Ford made some changes to their authentication service. I'm working on implementing the new changes! 😄

**Comment by ianjwhite99** [comment]
v1.2.5 has just been released and the issues you experienced while trying to authenticate and generated a refresh token should now be fixed. Please test and confirm. Thanks, Ian.

**Comment by Palmke** [comment]
Right now I am getting the following message from this PUT: https://github.com/ianjwhite99/connected-car-node-sdk/blob/stable/src/Authentication/OAuth2Client.ts#L113
`404 Resource Not Found: "{ "statusCode": 404, "message": "Resource not found" }"`

Region is EU btw

**Comment by sauravkumal** [comment]
same issue `'https://api.mps.ford.com/api/token/v2/cat-with-ci-access-token'` Resouce not found

**Comment by Palmke** [comment]
Had a look and as far as my Android app reverse engineering skills go, it got changed to  a `POST`.
I get tokens again when _not_ using `PUT`, but using `POST`.

**Comment by ianjwhite99** [comment]
> https://github.com/ianjwhite99/connected-car-node-sdk/blob/stable/src/Authentication/OAuth2Client.ts#L113

Thanks for catching that @Palmke. Should be fixed in [v1.2.6.](https://github.com/ianjwhite99/connected-car-node-sdk/releases/tag/v1.2.6)

**Comment by Palmke** [comment]
It seems they're still learning oauth over at Ford. While I don't get why they changed the endpoints with such weird names, at least now it uses a proper `POST` to get a token ;)

**Comment by ianjwhite99** [comment]
> It seems they're still learning oauth over at Ford. While I don't get why they changed the endpoints with such weird names, at least now it uses a proper `POST` to get a token ;)

I know right...the dev's over at Ford are finally starting to read the OAuth 2 specs 🤣
