### ISSUE TITLE
Add support for proxy

### ISSUE THREAD

**Issue by sauravkumal** [ianjwhite99/connected-car-node-sdk#31]
**Is your feature request related to a problem? Please describe.** A clear and concise description
of what the problem is. Ex. I'm always frustrated when [...]

I would like to request for a proxy feature. 

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Currently it works locally but when I run the program in digitalocean, it gets blocked.

**Describe alternatives you've considered** A clear and concise description of any alternative
solutions or features you've considered.

I had previously made it work in php using proxy, but recently they changed their auth flow. So I can't just always keep on changing
things. So i am using this package but it lacks proxy feature.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by sauravkumal** [comment]
for now I made it working by manually uploading token from local to server. Thanks

**Comment by ianjwhite99** [comment]
Hi, currently I do not have any plans to support a proxy integration.
