### ISSUE TITLE
Deploy in AWS Lambda

### ISSUE THREAD

**Issue by swamplynx** [ianjwhite99/connected-car-node-sdk#33]
I’d like to deploy this in AWS Lambda. I have some experience deploying small NodeJS functions, but have never deployed a python function. I imagine this might be a popular deployment option, so from a feature request perspective it would be great if the documentation included a “how to” get it running up there. I’m going to give it a whirl myself, but any time saving tips would be greatly appreciated.

**Comment by ianjwhite99** [comment]
Hi, please checkout the [connectedcar-node-api](https://github.com/ianjwhite99/connected-car-node-api). This is a middle-man api that I build that allows you to control your car from your own "personal" api. You can use serverless to deploy to AWS Lambda.
