### ISSUE TITLE
What's wrong with this request?

### ISSUE THREAD

**Issue by andig** [ianjwhite99/connected-car-node-sdk#36]
Not a bug, but a development question. I've re-implemented this api for https://github.com/evcc-io/evcc/discussions/4477 and fail to update to the latest changes from #35. Could I kindly ask you for advise what's wrong with this request? I can't seem to find any difference with this repo, yet always end in HTTP 404.

```
POST /api/expdashboard/v1/details HTTP/1.1
Host: api.mps.ford.com
User-Agent: FordPass/5 CFNetwork/1333.0.4 Darwin/21.5.0
Content-Length: 51
Accept: application/json
Application-Id: 1E8C7794-FF5F-49BC-9596-A1E0C86C5B19
Auth-Token: eyJ0...
Content-Type: application/json
Countrycode: EUR
Accept-Encoding: gzip

{"dashboardRefreshRequest":"All","smsWakeUpVIN":""}
```

Much appreciated, thank you!

**Comment by andig** [comment]
Ah, request is accepted with added locale (`en-US`) but doesn't go through then:

    {"requestStatus":null,"error":{"statusContext":"Invalid countryCode","statusCode":400,"message":"Invalid country in the request: EUR"},"lastRequested":null}

**Comment by andig** [comment]
Again working if I add `USA` instead of `EUR`. Not sure why. User is in Germany.

**Comment by ianjwhite99** [comment]
Hi,

If you set the locale in the headers to `"locale": "en-EU"` and countryCode to `"countryCode": "EUR"` does the request complete successfully?

**Comment by ianjwhite99** [comment]
I'm located in the US and I haven't gone through the process of creating accounts for different countries/regions.

**Comment by andig** [comment]
> If you set the locale in the headers to "locale": "en-EU" and countryCode to "countryCode": "EUR" does the request complete successfully?

Nope, neither:

    Countrycode: EUR
    Locale: en-EU

gives

    {"requestStatus":null,"error":{"statusContext":"Invalid countryCode","statusCode":400,"message":"Invalid country in the request: EUR"},"lastRequested":null}

Only this working is `en-US` with `USA`. That does seem to work though.

**UPDATE**

Finally found https://github.com/TA2k/ioBroker.ford/search?q=Countrycode. Which has also working `de-DE` with `DEU`:)
