### ISSUE TITLE
Ford Account Lockout

### ISSUE THREAD

**Issue by ianjwhite99** [ianjwhite99/connected-car-node-sdk#37]
Hi all,

It seems Ford has started cracking down on third party services taking advantage of their apis.

Recently I was locked out of my account and after speaking to Ford support they told me it was because of an unauthorized third party service using my credentials, which would be connected-car SDK's.

I am curious if anyone else has experienced this issue?

**Comment by brandon-grant** [comment]
I've encountered the same issue with multiple accounts. Calling Ford's APIs from a scheduled job is a sure fire way to get locked out...

Did Ford unlock your account?

**Comment by ianjwhite99** [comment]
> I've encountered the same issue with multiple accounts. Calling Ford's APIs from a scheduled job is a sure fire way to get locked out...
> 
> Did Ford unlock your account?

Not yet...they've asked me to contact the developer team directly. In your experience did they have you reach out to the development team?

I believe the reason for the account lock was attempting to login and generate an access token and refresh token too quickly. I use iOS shortcuts on my phone to start my truck, instead of building the use refresh token login, I just generated a new access token every time I wanted to run a command like start, lock, unlock, etc.

**Comment by brandon-grant** [comment]
> Not yet...they've asked me to contact the developer team directly. In your experience did they have you reach out to the development team?
> 
> I believe the reason for the account lock was attempting to login and generate an access token and refresh token too quickly. I use iOS shortcuts on my phone to start my truck, instead of building the use refresh token login, I just generated a new access token every time I wanted to run a command like start, lock, unlock, etc.

Apparently, support was communicating with the dev/security team. I was told that they could not unlock my account, so I requested it be deleted so that I could just remake the account. Support replied and said my account had been deleted and closed the issue, but my account was not deleted... It's been crickets ever since.

I also use iOS shortcuts in the same manner, but I don't believe they're the culprit for me.

**Comment by ianjwhite99** [comment]
Yeah, I was communicating with the support team as well but then they told me to reach out to the development team to speak more about unlocking my account. 

I went ahead and tried to find a solution and it seems like updating the User-Agent to the latest version did the trick in my case. 

I created a new account, used the latest FordPass UA and then redid my iOS Shortcuts to not force a new login every time.

So far so good.

**Comment by brandon-grant** [comment]
I'd guess you're probably right about the login/User-Agent being the problem. Multiple login attempts coming from an outdated UA definitely looks suspicious.

Let me know if you're able to get Ford to unlock your account. I'd like to get my original account back...
